### ISSUE TITLE
Crash in creative inventory

### ISSUE THREAD

**Issue by Breadabix** [Wealthyturtle/Minechem-1.7.10-Reworked#1]
When I click the arrow to go to the next page of tabs in the creative invetory, the game crashes. 

https://pastebin.com/8m0a5u7W

**Comment by Whimsyturtle** [comment]
I'm Assuming You're Running this on a Server Environment? Not Singleplayer?

**Comment by Breadabix** [comment]
It happens on both multiplayer and singleplayer

**Comment by Whimsyturtle** [comment]
Look like a recipe was corrupted. Which elements have a fire output? Use NEI.

**Comment by Breadabix** [comment]
You can use fire in a shapeless recipe to craft any element according to NEI. The recipe doesnt actually work though.

**Comment by Whimsyturtle** [comment]
Any fire-recipe that is not pertaining to an element?

**Comment by Breadabix** [comment]
None that I can see. There definitly isnt for any of the mods blocks/items. For the elements the fire recipe says it will make 8 of that element. Also if I click 'u' on fire in NEI it only shows that it can be used to craft chainmail armour, nothing to do with elements

**Comment by Whimsyturtle** [comment]
Does this occur in https://github.com/iopleke/Minechem/releases/tag/1.7.10-5.0.5.394 (Original Minechem Latest 1.7.10 Build)?

**Comment by Breadabix** [comment]
Not that I know of, I have an apparently later build, Minechem-1.7.10-5.0.5.406

**Comment by Breadabix** [comment]
It doesnt happen in the build I have

**Comment by Whimsyturtle** [comment]
Try https://github.com/iopleke/Minechem/releases/tag/1.7.10-5.0.5.394 since Minechem 1.7.10 Reworked is Built Ontop of that Build.

**Comment by Breadabix** [comment]
This version just crashes while trying to load up with it, https://pastebin.com/sftfTevU

**Comment by Whimsyturtle** [comment]
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: minechem/tileentity/synthesis/SynthesisTileEntity

Forge cannot find Minechem's SynthesisTileEntity.class. Probably a download error, reinstall Minechem 5.0.5.394

**Comment by Breadabix** [comment]
Reinstalling did nothing, still crashes :/. https://pastebin.com/xQyMtvkr

**Comment by Whimsyturtle** [comment]
Nope, this is something on your part. I downloaded it and it worked. Remove all your Walia and NEI components for the time being.

**Comment by Whimsyturtle** [comment]
Minechem-1.7.10-5.0.5.394.jar @ https://github.com/iopleke/Minechem/releases/tag/1.7.10-5.0.5.394

**Comment by Breadabix** [comment]
I have downloaded this, made a new profile on curse/twitch and only installed that version of minechem and it still happens. Crash report here in case it is different, doubt it though. https://pastebin.com/AqWFs9iu

And you said about it missing a file, just looked through the mod and found it, exactly where it should be and with the correct name. minechem/tileentity/synthesis/SynthesisTileEntity

**Comment by Whimsyturtle** [comment]
Where did you install the mod file? Give me the directory.
E.g.
F:\Minecraft\Minechem\mods\Minechem.jar

**Comment by Breadabix** [comment]
E:/Documents/Curse/Minecraft/Instances/[Instance name]/mods/Minechem-1.7.10-5.0.5.394.jar

**Comment by Breadabix** [comment]
Any news on this issue? Would love to replace now unsupported minechem with this one

**Comment by Breadabix** [comment]
Is there any progress on this?

**Comment by darthvader45** [comment]
@Breadabix Try the new latest release: https://github.com/Wealthyturtle/Minechem-1.7.10-Reworked/releases/download/v4/Minechem.Custom.Wealthyturtle.Build.V4.-1.7.10.jar

Should work.  Also, wonder if WealthyTurtle would be okay with teaming up with me to port this to 1.12.x?  Would love to use this with the newer versions of MC.

**Comment by Whimsyturtle** [comment]
@darthvader45 I believe that the Minechem team is already doing it.... Not very sure tho.

**Comment by Whimsyturtle** [comment]
@Breadabix I'll try and fix it again xD

**Comment by darthvader45** [comment]
Yeah, way2muchnoise was working on a 1.11.2 version recently.  Dunno if he's still working on it or not.

**Comment by Breadabix** [comment]
Any news on the attempt at fixing this?

**Comment by Breadabix** [comment]
Anything @Wealthyturtle?

**Comment by Breadabix** [comment]
@Wealthyturtle This is an old thread now but this is still an issue. 
Crash with other mods and sphax: https://pastebin.com/QG4tx5RV
Crash without other mods and sphax: https://pastebin.com/Y88UpCXg

**Comment by Whimsyturtle** [comment]
@Breadabix Try Version 6 of Minechem 1.7.10 Reworked now :)

**Comment by Whimsyturtle** [comment]
Please make another issue if this still isn't fixed in Version 6
