### ISSUE TITLE
Lacing food with chemicals

### ISSUE THREAD

**Issue by darthvader45** [Wealthyturtle/Minechem-1.7.10-Reworked#2]
Would it be possible in future versions of this rework to lace food with certain chemicals?  Like, say, potassium cyanide?  It was rather amusing to a user named cybercat5555 (a modeler for the AvP mod by Ri5ux).  Also, if you do decide to port to 1.11.2 and 1.12.2, perhaps compatibility with Jurassicraft would be in order?  Mainly because Minechem has Lysine, which is a protein most famously used in Jurassic Park, where the dinosaurs are genetically altered to be lysine-deficient, and had to have supplements added to their food.

**Comment by Whimsyturtle** [comment]
Unfortunately, this mod is mostly more of just to fix the bugs present in Minechem (1.7.10). I do not intend to port to future versions of Minecraft, since the Minechem team are probably working on it already. Please submit your suggestions to them, not to me. Thanks.
